spring:
  datasource:
    type: com.alibaba.druid.pool.DruidDataSource
    driverClassName: com.mysql.jdbc.Driver
    druid:
      url: jdbc:mysql://hushangrds.chq6n9anoaj2.rds.cn-north-1.amazonaws.com.cn:3306/ZH_xcx?allowMultiQueries=true&useUnicode=true&characterEncoding=UTF-8&useSSL=false
      username: xinliang
      password: dKeQZNjgIibt72aX
      #      first:  #数据源1
      #      url: jdbc:mysql://127.0.0.1:3306/gps_admin?allowMultiQueries=true&useUnicode=true&characterEncoding=UTF-8&useSSL=false
      #      username: root
      #      password: 123456

      #      second:  #数据源2
      #        url: jdbc:mysql://127.0.0.1:3306/gps_stat?allowMultiQueries=true&useUnicode=true&characterEncoding=UTF-8&useSSL=false
      #        username: root
      #        password: 123456
      initial-size: 10
      max-active: 100
      min-idle: 10
      max-wait: 60000
      pool-prepared-statements: true
      max-pool-prepared-statement-per-connection-size: 20
      time-between-eviction-runs-millis: 60000
      min-evictable-idle-time-millis: 300000
      #validation-query: SELECT 1 FROM DUAL
      test-while-idle: true
      test-on-borrow: false
      test-on-return: false
      stat-view-servlet:
        enabled: true
        url-pattern: /druid/*
        #login-username: admin
        #login-password: admin
      filter:
        stat:
          log-slow-sql: true
          slow-sql-millis: 1000
          merge-sql: false
        wall:
          config:
            multi-statement-allow: true
#  redis:
#    database: 8
#    host: 192.168.5.10
#    port: 6379
#    password:      # 密码（默认为空）
#    timeout: 6000ms  # 连接超时时长（毫秒）
#    jedis:
#      pool:
#        max-active: 1000  # 连接池最大连接数（使用负值表示没有限制）
#        max-wait: -1ms      # 连接池最大阻塞等待时间（使用负值表示没有限制）
#        max-idle: 10      # 连接池中的最大空闲连接
#        min-idle: 5       # 连接池中的最小空闲连接
login:
  api:
    ttx: /StandardApiAction_login.action      # 第三方平台登录api
ttx:
  accinfo:
    ip: 192.168.5.109
    port: 9008   #通天星业务服务模块端口
