# Tomcat
server:
  tomcat:
    uri-encoding: UTF-8
    max-threads: 1000
    min-spare-threads: 30
  port: 8080
#    servlet:
#        context-path: /renren-admin

# mysql
spring:
  # 环境 dev|test|prod
  datasource:
    type: com.alibaba.druid.pool.DruidDataSource
    driverClassName: com.mysql.jdbc.Driver
    url: jdbc:mysql://hushangrds.chq6n9anoaj2.rds.cn-north-1.amazonaws.com.cn:3306/ZH_xcx?allowMultiQueries=true&useUnicode=true&characterEncoding=UTF-8&useSSL=false
    username: xinliang
    password: dKeQZNjgIibt72aX
#    url: jdbc:mysql://127.0.0.1:3306/ZH_xcx?allowMultiQueries=true&useUnicode=true&characterEncoding=UTF-8&useSSL=false
#    username: root
#    password: 123456
      #      first:  #数据源1
      #      url: jdbc:mysql://127.0.0.1:3306/gps_admin?allowMultiQueries=true&useUnicode=true&characterEncoding=UTF-8&useSSL=false
      #      username: root
      #      password: 123456

    initial-size: 10
    max-active: 100
    min-idle: 10
    max-wait: 60000
    pool-prepared-statements: true
    max-pool-prepared-statement-per-connection-size: 20
    time-between-eviction-runs-millis: 60000
    min-evictable-idle-time-millis: 300000
      #validation-query: SELECT 1 FROM DUAL
    test-while-idle: true
    test-on-borrow: false
    test-on-return: false
    stat-view-servlet:
      enabled: true
      url-pattern: /druid/*
        #login-username: admin
        #login-password: admin
      filter:
        stat:
          log-slow-sql: true
          slow-sql-millis: 1000
          merge-sql: false
        wall:
          config:
            multi-statement-allow: true
  servlet:
    multipart:
      max-file-size: 100MB
      max-request-size: 100MB
      enabled: true
  #    freemarker:
  #      suffix: .html
  #      request-context-attribute: request
  thymeleaf:
    prefix: classpath:/templates/
    suffix: .html
    mode: LEGACYHTML5
    cache: false
  devtools:
    restart:
      enabled: false                 # 热部署开头，false即不启用
      exclude: static/**,public/**,templates/**  # 排除指定目录资源
    additional-paths: src/main/java  # 指定热部署目录
  #dubbo
#    dubbo:
#        application:
#            name: controller-consumer #本服务名称
#        registry:
#            address: zookeeper://127.0.0.1:2181 #zookeeper所在服务器的IP和端口
#        scan: com.xn.admin.modules.sys.service
#        protocol:
#            name: dubbo
#            port: 20883
xn:
  redis:
    open: false  # 是否开启redis缓存  true开启   false关闭
  shiro:
    redis: false # true表示shiro session存到redis里，需要开启redis，才会生效【分布式场景】

#mybatis
mybatis-plus:
  mapper-locations: classpath*:mapper/**/*.xml
  #实体扫描，多个package用逗号或者分号分隔
  typeAliasesPackage: com.xn.**.domain
  global-config:
    #主键类型  0:"数据库ID自增", 1:"用户输入ID",2:"全局唯一ID (数字类型唯一ID)", 3:"全局唯一ID UUID";
    id-type: 0
    #字段策略 0:"忽略判断",1:"非 NULL 判断"),2:"非空判断"
    field-strategy: 2
    #驼峰下划线转换
    db-column-underline: true
    #刷新mapper 调试神器
    refresh-mapper: true
    #数据库大写下划线转换
    #capital-mode: true
    # Sequence序列接口实现类配置
    #key-generator: com.baomidou.mybatisplus.incrementer.OracleKeyGenerator
    #逻辑删除配置
    logic-delete-value: -1
    logic-not-delete-value: 0
    #自定义填充策略接口实现
    #meta-object-handler: com.baomidou.springboot.xxx
    #自定义SQL注入器
    sql-injector: com.baomidou.mybatisplus.mapper.LogicSqlInjector
  configuration:
    map-underscore-to-camel-case: true
    cache-enabled: false
    call-setters-on-nulls: true


#服务器端视频解析接口地址
#vedioAnylysisUrl: http://47.103.143.95/api/url
vedioAnylysisUrl: http://video.resolv.zhanghi.net/api/url
#商家收益比例
serverDivident: 0.1
#上级用户收益比例
highDivident: 0.6
#上上级用户收益比例
superiorDivident: 0.3
#会员价格
vipPrice: 9900
#代理价格
agentPrice: 29900
#小程序AppId
APPID: wx3dd2d1920aa87889
#小程序secret
Secret: 08d24121d6ea45e698f7a6b38b551300
#微信登录授权认证code校验API
AUTH_CODE_URL: https://api.weixin.qq.com/sns/jscode2session?appid=APPID&secret=SECRET&js_code=JSCODE&grant_type=authorization_code
#微信统一下单API
WX_ORDER_CREAT: https://api.mch.weixin.qq.com/pay/unifiedorder
#微信支付回调地址
wxPayCallBackUrl: HTTP://54.110.42.148:8080/user/{openId}/{orderId}/wpayCalbak
#微信退款
wxPayBackUrl: https://api.mch.weixin.qq.com/mmpaymkttransfers/promotion/transfers
#商户ID
MCH_ID: 1584262561
#商户秘钥 key
MCH_KEY: 5213BE07944125A1B0C10732F12B64C3


logging:
  level: debug
  level.com: debug
  path: logs/
  file: admin.log
sync:
  redis: false   # 用户、机构、车辆数据是否同步至redis
constant:
  active-device: VEHICLE_GB809
login:
  api:
    ttx: /StandardApiAction_login.action      # 第三方平台登录api
ttx:
  accinfo:
    ip: 192.168.5.109
    port: 9008   #通天星业务服务模块端口